version: "3.9"

services:
  flask:
    build: .
    container_name: picresize_gunicorn
    restart: always
    volumes:
      - ./originalzip:/app/originalzip
      - ./resized:/app/resized
      - ./resizedzip:/app/resizedzip
      - ./original/:/app/original
    ports:
      - "8004:8004"
